Navbar1
mantecajc/massages-shop pull request #5
Opened 2023-06-09 15:48 UTC by Miguelcuad

2023-06-10 12:26 UTC, mantecajc requested changes

2023-06-10 12:26 UTC, mantecajc commented on app/views/layouts/application.html.erb
> +      function openMenu() {
Aquí viene Paco con las rebajas 😂 

Todo esto que está comentado lo puedes quitar

2023-06-10 12:26 UTC, mantecajc commented on app/views/layouts/application.html.erb
> +        <img src="<%= asset_path 'logo.svg' %>" alt="logo" class="w-[80px] h-[70px] md:w-[120px] md:h-[120px]">
Se me olvidó decirte, hay que poner un link_to en el logo que nos redirija a la home page. Por el momento no nos sirve para nada, pero servirá 😂

2023-06-10 12:26 UTC, mantecajc commented on app/views/layouts/application.html.erb
> +    <nav class="navbar h-[80px] md:h-[100px]">
La navbar tiene este border bottom en la maqueta 
<img width="484" alt="Captura de pantalla 2023-06-10 a las 14 10 53" src="https://github.com/mantecajc/massages-shop/assets/65590523/0817bd1f-9afb-44d4-a20a-3384a98c0966">

2023-06-10 12:26 UTC, mantecajc commented on app/views/layouts/application.html.erb
> +        <a href="#" class="py-5 md:mr-6 md:py-0">Les massages</a>
Para el tipo de police, ya puedes recuperarla del fichero `tailwind.config.js`. Ahí podemos personalizar las clases tailwind o hacerlas caseras 😂  Solo tienes que añadir esto a tu clase `font-comfortaa`

Ah sí, ¿puedes poner un font size de `1.1rem`? Luego ya ajustaremos pero hace muy tocho sino hahaha

2023-06-10 12:26 UTC, mantecajc commented on app/views/layouts/application.html.erb
> +      <div class="nav_logo mt-2 ml-11 md:ml-36 md:mt-3">
A lo mejor no merece la pena, pero qué te parece si metemos el código de la navbar en un parcial y lo llamamos en application.html.erb. Así lo tenemos todo más ordenadito

Pues crear una carpeta shared en `app/views/shared/_navbar.html.erb`

Lo mismo para el script JS, creas un archivo en `app/javascript` y lo importas en `javascript/application.js`

2023-06-11 10:10 UTC, Miguelcuad commented on app/views/layouts/application.html.erb
> +    <nav class="navbar h-[80px] md:h-[100px]">
Estaba puesto, en algún momento se fue al garete.

2023-06-11 10:14 UTC, Miguelcuad commented on app/views/layouts/application.html.erb
> +      <div class="nav_logo mt-2 ml-11 md:ml-36 md:mt-3">
el primero lo creo con el nombre de _navbar.html.erb?
En lo segundo lo llamo -navbar también?

2023-06-11 10:15 UTC, Miguelcuad commented on app/views/layouts/application.html.erb
> +      <div class="nav_logo mt-2 ml-11 md:ml-36 md:mt-3">
es decir _navbar.js**

2023-06-11 10:19 UTC, Miguelcuad commented on app/views/layouts/application.html.erb
> +        <a href="#" class="py-5 md:mr-6 md:py-0">Les massages</a>
Quieres decir que en el archivo tailwind.config.js haga casera la clase font-comfortaa a 1.1rem para todo el texto de la navbar. Arriba en el código puse diferentes medidas, para sd 26px y a partir de md 22px.

2023-06-11 11:01 UTC, mantecajc commented on app/views/layouts/application.html.erb
> +        <a href="#" class="py-5 md:mr-6 md:py-0">Les massages</a>
No, el 1.1rem ponlo directamente en el html como el resto del tailwind

2023-06-11 11:02 UTC, mantecajc commented on app/views/layouts/application.html.erb
> +      <div class="nav_logo mt-2 ml-11 md:ml-36 md:mt-3">
Sí el primero _navbar.html.erb está bien, y el segundo _navbar.js o _toggle_burgermenu.js o algo así

2023-06-11 12:53 UTC, mantecajc commented on app/assets/stylesheets/navbar.css
> +.nav_toggle{
Ahhh ! Los nombres de clases, ids.. en CSS se escriben así nav-toggle con el guión en el medio. Muy bien explicado aquí https://www.freecodecamp.org/espanol/news/convenciones-de-nomenclatura-de-css-que-te-ahorraran-horas-de-depuracion/

2023-06-15 19:07 UTC, mantecajc commented
outdate

2023-06-15 19:07 UTC, closed without merging